export const burdens = [
  "Arnor-ravaged.jpg",
  "Gandalf's-Delay.jpg",
  "Graxar.jpg",
  "Guilty-Conscience.jpg",
  "Ill-Fate.jpg",
  "Losing-Time.jpg",
  "Lust-for-the Ring.jpg",
  "Overcome-by-Grief.jpg",
  "overcome-by-terror.jpg",
  "Panicked.jpg",
  "Persued-by-the-Enemy.jpg",
  "Protect-the-Innocent.jpg",
  "Scarred.jpg",
  "Stalking-Goblin.jpg",
  "Thaurdir's-Legacy.jpg",
  "Thaurdir's-Spite.jpg",
  "The-Searching-Eye.jpg",
  "Weight-of-the-ring.jpg",
];
