export const clonedHeroes = [
  {
    pack_code: "WitW",
    pack_name: "The Watcher in the Water",
    type_code: "hero",
    type_name: "Hero",
    sphere_code: "lore",
    sphere_name: "Lore",
    position: 53,
    code: "04053",
    name: "Aragorn",
    traits: "Dúnedain. Ranger.",
    text: "Sentinel.\n<b>Refresh Action:</b> Reduce your threat to your starting threat level. (Limit once per game.)",
    flavor:
      '"I am older than I look, I might prove useful."\n<cite>The Fellowship of the Ring</cite>',
    is_unique: true,
    threat: 12,
    willpower: 2,
    attack: 3,
    defense: 2,
    health: 5,
    quantity: 1,
    deck_limit: 1,
    illustrator: "Tony Foti",
    octgnid: "51223bd0-ffd1-11df-a976-0801210c9001",
    has_errata: false,
    url: "https://ringsdb.com/card/04053",
    imagesrc: "/bundles/cards/04053.png",
    alive: true,
    current: false,
  },
  {
    pack_code: "FoS",
    pack_name: "Foundations of Stone",
    type_code: "hero",
    type_name: "Hero",
    sphere_code: "spirit",
    sphere_name: "Spirit",
    position: 101,
    code: "04101",
    name: "Glorfindel",
    traits: "Noldor. Noble. Warrior.",
    text: "<b>Forced:</b> After Glorfindel exhausts to commit to a quest, raise your threat by 1.",
    flavor:
      "Glorfindel was tall and straight; his hair was of shining gold, his face fair and young and fearless and full of joy; his eyes were bright and keen, and has voice like music; on his brow sat wisdom, and in his hand was strength.\n<cite>The Fellowship of the Ring</cite>",
    is_unique: true,
    threat: 5,
    willpower: 3,
    attack: 3,
    defense: 1,
    health: 5,
    quantity: 1,
    deck_limit: 1,
    illustrator: "Magali Villeneuve",
    octgnid: "51223bd0-ffd1-11df-a976-0801212c9016",
    has_errata: false,
    url: "https://ringsdb.com/card/04101",
    imagesrc: "/bundles/cards/04101.png",
    alive: true,
    current: false,
  },
  {
    pack_code: "HoN",
    pack_name: "Heirs of Númenor",
    type_code: "hero",
    type_name: "Hero",
    sphere_code: "leadership",
    sphere_name: "Leadership",
    position: 2,
    code: "05002",
    name: "Boromir",
    traits: "Gondor. Warrior. Noble.",
    text: "While Boromir has at least 1 resource in his resource pool, <b><i>Gondor</i></b> allies get +1 [attack].",
    flavor:
      '"By our valour the wild fold of the East are still restrained, and the terror of Morgul kept at bay..." <cite>The Fellowship of the Ring</cite>',
    is_unique: true,
    threat: 11,
    willpower: 1,
    attack: 3,
    defense: 2,
    health: 5,
    quantity: 1,
    deck_limit: 1,
    illustrator: "Magali Villeneuve",
    octgnid: "4823aae3-46ef-4a75-89f9-cbd3aa1b9008",
    has_errata: false,
    url: "https://ringsdb.com/card/05002",
    imagesrc: "/bundles/cards/05002.png",
    alive: true,
    current: false,
  },
  {
    pack_code: "TLR",
    pack_name: "The Lost Realm",
    type_code: "hero",
    type_name: "Hero",
    sphere_code: "tactics",
    sphere_name: "Tactics",
    position: 1,
    code: "09001",
    name: "Aragorn",
    traits: "Dúnedain. Ranger. Warrior.",
    text: "Each enemy engaged with you gets -1 [defense].\n<b>Response:</b> After Aragorn participates in an attack that destroys an enemy, choose an enemy not engaged with you and engage that enemy.",
    flavor:
      '"I serve no man," said Aragorn; "but the servants of Sauron I pursue into whatever land they may go." <cite>The Two Towers</cite>',
    is_unique: true,
    threat: 12,
    willpower: 2,
    attack: 3,
    defense: 2,
    health: 5,
    quantity: 1,
    deck_limit: 1,
    illustrator: "Sebastian Giacobino",
    octgnid: "09ebd71c-8286-4838-b661-36a8633c9f0c",
    has_errata: false,
    url: "https://ringsdb.com/card/09001",
    imagesrc: "/bundles/cards/09001.png",
    alive: true,
    current: false,
  },
  {
    pack_code: "FotS",
    pack_name: "Flight of the Stormcaller",
    type_code: "hero",
    type_name: "Hero",
    sphere_code: "leadership",
    sphere_name: "Leadership",
    position: 1,
    code: "12001",
    name: "Denethor",
    traits: "Gondor. Noble. Steward.",
    text: "<b>Setup:</b> Add 2 resources to Denethor's resource pool.\n<b>Action:</b> Move 1 resource from Denethor's resource pool to another <b><i>Gondor</i></b> hero's resource pool. (Limit once per round.)",
    flavor:
      '"...why should I sit here in my tower and think, and watch, and wait, spending even my sons? For I can still wield a brand." <cite>The Return of the King</cite>',
    is_unique: true,
    threat: 8,
    willpower: 1,
    attack: 1,
    defense: 3,
    health: 3,
    quantity: 1,
    deck_limit: 1,
    illustrator: "Joshua Cairós",
    octgnid: "4a76ad60-35d1-4657-ab4a-2f7f15cc7ab7",
    has_errata: false,
    url: "https://ringsdb.com/card/12001",
    imagesrc: "/bundles/cards/12001.png",
    alive: true,
    current: false,
  },
  {
    pack_code: "CoC",
    pack_name: "The City of Corsairs",
    type_code: "hero",
    type_name: "Hero",
    sphere_code: "tactics",
    sphere_name: "Tactics",
    position: 138,
    code: "12138",
    name: "Prince Imrahil",
    traits: "Gondor. Noble. Warrior.",
    text: "<b>Combat Action:</b> Spend 1 resource from Prince Imrahil's resource pool to search the top 5 cards of your deck for an ally who shares at least 1 <b><i>Trait</i></b> with him, and put that ally into play. Shuffle your deck. At the end of the phase, if that ally is still in play, shuffle it into your deck. (Limit once per round.)",
    is_unique: true,
    threat: 11,
    willpower: 2,
    attack: 3,
    defense: 2,
    health: 4,
    quantity: 1,
    deck_limit: 1,
    illustrator: "Unknown",
    octgnid: "66cf39b5-015f-4bae-b304-4a61b5d1bedf",
    has_errata: false,
    url: "https://ringsdb.com/card/12138",
    imagesrc: "/bundles/cards/12138.png",
    alive: true,
    current: false,
  },
  {
    pack_code: "OHaUH",
    pack_name: "Over Hill and Under Hill",
    type_code: "hero",
    type_name: "Hero",
    sphere_code: "baggins",
    sphere_name: "Baggins",
    position: 1,
    code: "131001",
    name: "Bilbo Baggins",
    traits: "Hobbit.",
    text: "The first player gains control of Bilbo Baggins.\r\nBilbo Baggins cannot gain resources from player card effects.\r\n<b>If Bilbo Baggins leaves play, the players lose the game.</b>",
    is_unique: true,
    threat: 0,
    willpower: 1,
    attack: 1,
    defense: 1,
    health: 3,
    quantity: 1,
    deck_limit: 1,
    illustrator: "Magali Villeneuve",
    octgnid: "51223bd0-ffd1-11df-a976-1801204c9017",
    has_errata: false,
    url: "https://ringsdb.com/card/131001",
    imagesrc: "/bundles/cards/131001.png",
    alive: true,
    current: false,
  },
  {
    pack_code: "OtD",
    pack_name: "On the Doorstep",
    type_code: "hero",
    type_name: "Hero",
    sphere_code: "baggins",
    sphere_name: "Baggins",
    position: 1,
    code: "132001",
    name: "Bilbo Baggins",
    traits: "Hobbit. Burglar.",
    text: "Bilbo Baggins does not count against the hero limit and cannot gain resources from non-treasure cards. The first player gains control of Bilbo Baggins.\r\n<b>Action:</b> Spend 1 [baggins] resource to search your deck for a treasure card and add it to your hand.\r\n<b>If Bilbo Baggins leaves play, the players have lost the game.</b>",
    is_unique: true,
    threat: 0,
    willpower: 1,
    attack: 1,
    defense: 1,
    health: 3,
    quantity: 1,
    deck_limit: 1,
    illustrator: "Magali Villeneuve",
    octgnid: "4e61b160-2104-497f-9977-4b353e54fbb7",
    has_errata: false,
    url: "https://ringsdb.com/card/132001",
    imagesrc: "/bundles/cards/132001.png",
    alive: true,
    current: false,
  },
  {
    pack_code: "TBR",
    pack_name: "The Black Riders",
    type_code: "hero",
    type_name: "Hero",
    sphere_code: "fellowship",
    sphere_name: "Fellowship",
    position: 1,
    code: "141001",
    name: "Frodo Baggins",
    traits: "Hobbit. Ring-bearer.",
    text: "<b>Response:</b> Spend 1 [fellowship] resource and exhaust The One Ring to cancel the effect of an encounter card just revealed from the encounter deck. Shuffle that card back into the encounter deck and reveal another encounter card.",
    flavor:
      '"I will take the Ring," he said, "though I do not know the way." <cite>The Fellowship of the Ring</cite>',
    is_unique: true,
    threat: 0,
    willpower: 2,
    attack: 1,
    defense: 2,
    health: 2,
    quantity: 1,
    deck_limit: 1,
    illustrator: "Jake Murray",
    octgnid: "3217a119-6b86-47dd-b451-c5e45be3f874",
    has_errata: false,
    url: "https://ringsdb.com/card/141001",
    imagesrc: "/bundles/cards/141001.png",
    alive: true,
    current: false,
  },
  {
    pack_code: "TBR",
    pack_name: "The Black Riders",
    type_code: "hero",
    type_name: "Hero",
    sphere_code: "tactics",
    sphere_name: "Tactics",
    position: 3,
    code: "141003",
    name: "Merry",
    traits: "Hobbit.",
    text: "Merry gets +1 [attack] for each Hobbit hero you control.\n<b>Response:</b> After Merry participates in an attack that destroys an enemy, ready another character that participated in that attack.",
    flavor:
      '"You can trust us to stick to you through thick and thin to the bitter end" <cite>The Fellowship of the Ring</cite>',
    is_unique: true,
    threat: 6,
    willpower: 2,
    attack: 0,
    defense: 1,
    health: 2,
    quantity: 1,
    deck_limit: 1,
    illustrator: "Alexandre Dainche",
    octgnid: "052b1f85-8b9c-4bb0-a735-bdbd5ac1b2c4",
    has_errata: false,
    url: "https://ringsdb.com/card/141003",
    imagesrc: "/bundles/cards/141003.png",
    alive: true,
    current: false,
  },
  {
    pack_code: "TBR",
    pack_name: "The Black Riders",
    type_code: "hero",
    type_name: "Hero",
    sphere_code: "lore",
    sphere_name: "Lore",
    position: 4,
    code: "141004",
    name: "Pippin",
    traits: "Hobbit.",
    text: "Each enemy in play gets +1 engagement cost for each <b><i>Hobbit</i></b> hero you control.\n<b>Response:</b> After you engage an enemy with an engagement cost higher than your threat, draw a card.",
    flavor:
      '"We Hobbits ought to stick together, and we will"\n<cite>The Fellowship of the Ring</cite>',
    is_unique: true,
    threat: 6,
    willpower: 2,
    attack: 1,
    defense: 1,
    health: 2,
    quantity: 1,
    deck_limit: 1,
    illustrator: "Alexandre Dainche",
    octgnid: "ce96b767-c569-48b8-a998-d8009b0143c7",
    has_errata: false,
    url: "https://ringsdb.com/card/141004",
    imagesrc: "/bundles/cards/141004.png",
    alive: true,
    current: false,
  },
  {
    pack_code: "TRD",
    pack_name: "The Road Darkens",
    type_code: "hero",
    type_name: "Hero",
    sphere_code: "fellowship",
    sphere_name: "Fellowship",
    position: 1,
    code: "142001",
    name: "Frodo Baggins",
    traits: "Hobbit. Ring-bearer.",
    text: "<b>Response:</b> After Frodo Baggins exhausts to defend an attack, exhaust The One Ring and spend 1 [fellowship] resource to target the attacking enemy. Then, this attack deals no damage and each player raises his threat by 2.",
    flavor:
      '"But there is more about you now than appears on the surface." <cite>Bilbo, The Fellowship of the Ring</cite>',
    is_unique: true,
    threat: 0,
    willpower: 2,
    attack: 1,
    defense: 2,
    health: 2,
    quantity: 1,
    deck_limit: 1,
    illustrator: "Sebastian Giacobino",
    octgnid: "f9196cda-8f50-4cc5-9aad-1c56cb677bca",
    has_errata: false,
    url: "https://ringsdb.com/card/142001",
    imagesrc: "/bundles/cards/142001.png",
    alive: true,
    current: false,
  },
  {
    pack_code: "ToS",
    pack_name: "The Treason of Saruman",
    type_code: "hero",
    type_name: "Hero",
    sphere_code: "fellowship",
    sphere_name: "Fellowship",
    position: 1,
    code: "143001",
    name: "Aragorn",
    traits: "Dúnedain. Noble. Ranger.",
    text: "The first player gains control of Aragorn. If Aragorn leaves play, the players lose the game.\n<b>Action:</b> Spend 2 resources from Aragorn's resource pool to ready a hero.",
    flavor:
      '"I am Aragorn son of Arathorn and am called Elessar, the Elfstone, Dunadan, the heir of Isildur Elendil’s son of Gondor."\n<cite>The Two Towers</cite>',
    is_unique: true,
    threat: 0,
    willpower: 2,
    attack: 3,
    defense: 2,
    health: 5,
    quantity: 1,
    deck_limit: 1,
    illustrator: "Mark Behm",
    octgnid: "f5178135-1485-43c5-9660-99232a4cdca8",
    has_errata: false,
    url: "https://ringsdb.com/card/143001",
    imagesrc: "/bundles/cards/143001.png",
    alive: true,
    current: false,
  },
  {
    pack_code: "ToS",
    pack_name: "The Treason of Saruman",
    type_code: "hero",
    type_name: "Hero",
    sphere_code: "spirit",
    sphere_name: "Spirit",
    position: 2,
    code: "143002",
    name: "Théoden",
    traits: "Rohan. Noble. Warrior.",
    text: "Sentinel.\nReduce the cost of the first <b><i>Rohan</i></b> ally you play from your hand each round by 1 (to a minimum of 0).",
    flavor:
      '"Arise now, arise, Riders of Théoden!" <cite>The Two Towers</cite>',
    is_unique: true,
    threat: 12,
    willpower: 2,
    attack: 3,
    defense: 2,
    health: 4,
    quantity: 1,
    deck_limit: 1,
    illustrator: "Tiziano Baracchi",
    octgnid: "f3d88160-30f2-4b8b-9e83-c42e62851bbc",
    has_errata: false,
    url: "https://ringsdb.com/card/143002",
    imagesrc: "/bundles/cards/143002.png",
    alive: true,
    current: false,
  },
  {
    pack_code: "LoS",
    pack_name: "The Land of Shadow",
    type_code: "hero",
    type_name: "Hero",
    sphere_code: "fellowship",
    sphere_name: "Fellowship",
    position: 1,
    code: "144001",
    name: "Frodo Baggins",
    traits: "Hobbit. Ring-bearer.",
    text: "<b>Action:</b> Spend 1 [fellowship] resource and exhaust The One Ring to give Frodo Baggins +2 [willpower] and +2 [attack] until the end of the round.",
    flavor:
      '"It\'s my doom, I think, to go to that Shadow yonder, so that a way will be found." <cite>The Two Towers</cite>',
    is_unique: true,
    threat: 0,
    willpower: 2,
    attack: 1,
    defense: 2,
    health: 2,
    quantity: 1,
    deck_limit: 1,
    illustrator: "Melanie Maier",
    octgnid: "fe58a6d3-7028-41c1-ab00-5e33e7d77b5f",
    has_errata: false,
    url: "https://ringsdb.com/card/144001",
    imagesrc: "/bundles/cards/144001.png",
    alive: true,
    current: false,
  },
  {
    pack_code: "LoS",
    pack_name: "The Land of Shadow",
    type_code: "hero",
    type_name: "Hero",
    sphere_code: "leadership",
    sphere_name: "Leadership",
    position: 2,
    code: "144002",
    name: "Faramir",
    traits: "Gondor. Noble. Ranger.",
    text: "Ranged.\n<b>Response:</b> After you engage an enemy, ready an ally you control. (Limit once per phase.)",
    flavor:
      '"That will be the Captain: he can master both beasts and men" <cite>Beregond, The Return of the King</cite>',
    is_unique: true,
    threat: 11,
    willpower: 2,
    attack: 2,
    defense: 2,
    health: 5,
    quantity: 1,
    deck_limit: 1,
    illustrator: "Jason Cheeseman Meyer",
    octgnid: "8f937f89-b248-4261-9b00-4e3cd9763299",
    has_errata: false,
    url: "https://ringsdb.com/card/144002",
    imagesrc: "/bundles/cards/144002.png",
    alive: true,
    current: false,
  },
  {
    pack_code: "FotW",
    pack_name: "The Flame of the West",
    type_code: "hero",
    type_name: "Hero",
    sphere_code: "fellowship",
    sphere_name: "Fellowship",
    position: 1,
    code: "145001",
    name: "Aragorn",
    traits: "Dúnedain. Noble. Ranger.",
    text: "The first player gains control of Aragorn. If Aragorn leaves play,the players lose the game.\nWhile Aragorn has an <b><i>Artifact</i></b> attached, he gains sentinel and does not exhaust to quest.",
    flavor:
      '"I have no help to send, therefore I must go myself..."\n<cite>The Return of the King</cite>',
    is_unique: true,
    threat: 0,
    willpower: 2,
    attack: 3,
    defense: 2,
    health: 5,
    quantity: 1,
    deck_limit: 1,
    illustrator: "Javier Charro Martinez",
    octgnid: "2e778689-9e3f-4da8-a473-781c777f6473",
    has_errata: false,
    url: "https://ringsdb.com/card/145001",
    imagesrc: "/bundles/cards/145001.png",
    alive: true,
    current: false,
  },
  {
    pack_code: "FotW",
    pack_name: "The Flame of the West",
    type_code: "hero",
    type_name: "Hero",
    sphere_code: "tactics",
    sphere_name: "Tactics",
    position: 2,
    code: "145002",
    name: "Éowyn",
    traits: "Rohan. Noble.",
    text: "<b>Setup:</b> Reduce your threat by 3.\n<b>Action:</b> Raise your threat by 3 to ready Éowyn. She gets +9 [attack] until the end of the phase. (Limit once per game for the group.)",
    flavor:
      '"But no living man am I! You look upon a woman. Éowyn I am, Éomund\'s daughter."\n<cite>The Return of the King</cite>',
    is_unique: true,
    threat: 9,
    willpower: 4,
    attack: 1,
    defense: 1,
    health: 3,
    quantity: 1,
    deck_limit: 1,
    illustrator: "Magali Villeneuve",
    octgnid: "6dc19efc-af54-4eff-b9ee-ee45e9fd4072",
    has_errata: false,
    url: "https://ringsdb.com/card/145002",
    imagesrc: "/bundles/cards/145002.png",
    alive: true,
    current: false,
  },
  {
    pack_code: "FotW",
    pack_name: "The Flame of the West",
    type_code: "hero",
    type_name: "Hero",
    sphere_code: "spirit",
    sphere_name: "Spirit",
    position: 3,
    code: "145003",
    name: "Beregond",
    traits: "Gondor. Warrior.",
    text: "Sentinel.\r\n<b>Response:</b> After Beregond defends an attack and takes no damage, reduce the defending player's threat by 1. (Limit once per round.)",
    flavor:
      '"The Lord does not permit those who wear the black and silver to leave their post for any cause..."\r\n<cite>The Return of the King</cite>',
    is_unique: true,
    threat: 10,
    willpower: 0,
    attack: 1,
    defense: 4,
    health: 4,
    quantity: 1,
    deck_limit: 1,
    illustrator: "Adam Lane",
    octgnid: "da4c926c-7917-4b6d-a1be-cc90fbdce597",
    has_errata: false,
    url: "https://ringsdb.com/card/145003",
    imagesrc: "/bundles/cards/145003.png",
    alive: true,
    current: false,
  },
  {
    pack_code: "MoF",
    pack_name: "The Mountain of Fire",
    type_code: "hero",
    type_name: "Hero",
    sphere_code: "fellowship",
    sphere_name: "Fellowship",
    position: 1,
    code: "146001",
    name: "Frodo Baggins",
    traits: "Hobbit. Ring-bearer.",
    text: "<b>Planning Action:</b> Exhaust The One Ring to add 1 resource to a hero's pool. ",
    flavor:
      '"I must carry the burden to the end." <cite>The Return of the King</cite>',
    is_unique: true,
    threat: 0,
    willpower: 2,
    attack: 1,
    defense: 2,
    health: 2,
    quantity: 1,
    deck_limit: 1,
    illustrator: "Aleksander Karcz",
    octgnid: "b937644c-ccbb-4a39-ae3c-24857d1d4d57",
    has_errata: false,
    url: "https://ringsdb.com/card/146001",
    imagesrc: "/bundles/cards/146001.png",
    alive: true,
    current: false,
  },
  {
    pack_code: "MoF",
    pack_name: "The Mountain of Fire",
    type_code: "hero",
    type_name: "Hero",
    sphere_code: "fellowship",
    sphere_name: "Fellowship",
    position: 2,
    code: "146002",
    name: "Aragorn",
    traits: "Dunedain. Gondor. Noble. Warrior.",
    text: "Sentinel. The first player gains control of Aragorn.\n<b>Action:</b> Spend 1 resource from Aragorn's pool to ready him. (Limit once per phase.)\n<b>If Aragorn leaves play, the players lose the game.</b>",
    flavor:
      '"As I have begun, so I will go on.." <cite>The Return of the King</cite>',
    is_unique: true,
    threat: 0,
    willpower: 2,
    attack: 3,
    defense: 2,
    health: 5,
    quantity: 1,
    deck_limit: 1,
    illustrator: "David A. Nash",
    octgnid: "f1cc6057-ced3-4105-9172-869d26a54af5",
    has_errata: false,
    url: "https://ringsdb.com/card/146002",
    imagesrc: "/bundles/cards/146002.png",
    alive: true,
    current: false,
  },
  {
    pack_code: "MoF",
    pack_name: "The Mountain of Fire",
    type_code: "hero",
    type_name: "Hero",
    sphere_code: "leadership",
    sphere_name: "Leadership",
    position: 3,
    code: "146003",
    name: "Éomer",
    traits: "Rohan. Noble. Warrior.",
    text: "<b>Response:</b> After Éomer commits to the quest, spend 1 resource from his resource pool to immediately declare him as an attacker (and resolve his attack) against an enemy in the staging area. ",
    flavor:
      "...he was young, and he was king; the lord of a fell people. <cite>The Return of the King</cite>",
    is_unique: true,
    threat: 10,
    willpower: 1,
    attack: 3,
    defense: 2,
    health: 4,
    quantity: 1,
    deck_limit: 1,
    illustrator: "Ryan Valle",
    octgnid: "7a1bc81a-c226-4589-a1cf-65668846c64b",
    has_errata: false,
    url: "https://ringsdb.com/card/146003",
    imagesrc: "/bundles/cards/146003.png",
    alive: true,
    current: false,
  },
  {
    pack_code: "TSoH",
    pack_name: "The Sands of Harad",
    type_code: "hero",
    type_name: "Hero",
    sphere_code: "leadership",
    sphere_name: "Leadership",
    position: 1,
    code: "16001",
    name: "Gimli",
    traits: "Dwarf. Noble. Warrior.",
    text: "Sentinel.\r\n<b>Response:</b> After Gimli is declared as a defender, spend 1 resource from his pool to ready another hero. If that hero is Legolas, he gets +1[attack] until the end of the phase. (Limit once per phase.)",
    flavor:
      '"Faithless is he that says farewell when the road darkens…"\r\n<cite>The Fellowship of the Ring</cite>',
    is_unique: true,
    threat: 11,
    willpower: 2,
    attack: 2,
    defense: 2,
    health: 5,
    quantity: 1,
    deck_limit: 1,
    illustrator: "Owen William Weber",
    octgnid: "053357f5-4192-4a35-bf2c-7f48d584f292",
    has_errata: false,
    url: "https://ringsdb.com/card/16001",
    imagesrc: "/bundles/cards/16001.png",
    alive: true,
    current: false,
  },
  {
    pack_code: "TSoH",
    pack_name: "The Sands of Harad",
    type_code: "hero",
    type_name: "Hero",
    sphere_code: "spirit",
    sphere_name: "Spirit",
    position: 2,
    code: "16002",
    name: "Legolas",
    traits: "Silvan. Noble. Scout.",
    text: "Ranged.\n<b>Response:</b> After Legolas commits to a quest, discard a card from your hand to ready another hero. If that hero is Gimli, he gets +1[willpower] until the end of the phase. (Limit once per phase.)",
    flavor: '"I go to find the Sun!"\n<cite>The Fellowship of the Ring</cite>',
    is_unique: true,
    threat: 9,
    willpower: 1,
    attack: 3,
    defense: 1,
    health: 4,
    quantity: 1,
    deck_limit: 1,
    illustrator: "Aleksander Karcz",
    octgnid: "8124f5ac-6f03-4629-96f5-b8775ec8a7c4",
    has_errata: false,
    url: "https://ringsdb.com/card/16002",
    imagesrc: "/bundles/cards/16002.png",
    alive: true,
    current: false,
  },
  {
    pack_code: "TWoR",
    pack_name: "The Wilds of Rhovanion",
    type_code: "hero",
    type_name: "Hero",
    sphere_code: "leadership",
    sphere_name: "Leadership",
    position: 1,
    code: "18001",
    name: "Brand son of Bain",
    traits: "Dale. Noble.",
    text: "Each <b><i>Dale</i></b> character you control with a player attachment gets +1 [willpower].\r\n<b>Response:</b> After you play an attachment on a <b><i>Dale</i></b> character without an attachment, draw a card.",
    flavor:
      '"He is a strong king, and his realm now reaches south and east of Esgaroth."\r\n<cite>Glóin, The Fellowship of the Ring</cite>',
    is_unique: true,
    threat: 10,
    willpower: 2,
    attack: 3,
    defense: 2,
    health: 3,
    quantity: 1,
    deck_limit: 1,
    illustrator: "Antonio José Manzanedo",
    octgnid: "2b75792d-5873-4fc6-9272-d20dd517d36b",
    has_errata: false,
    url: "https://ringsdb.com/card/18001",
    imagesrc: "/bundles/cards/18001.png",
    alive: true,
    current: false,
  },
  {
    pack_code: "TGoF",
    pack_name: "The Ghost of Framsburg",
    type_code: "hero",
    type_name: "Hero",
    sphere_code: "spirit",
    sphere_name: "Spirit",
    position: 84,
    code: "19084",
    name: "Dáin Ironfoot",
    traits: "Dwarf. Noble. Warrior.",
    text: "While Dáin Ironfoot is defending, he gains, '<b>Action</b>: Discard the top card of your deck to give Dáin Ironfoot +1 [defense] for this attack. (Limit 3 times per phase.)'",
    flavor: "",
    is_unique: true,
    threat: 11,
    willpower: 1,
    attack: 2,
    defense: 3,
    health: 5,
    quantity: 1,
    deck_limit: 1,
    illustrator: "Alexander Kozachenko",
    octgnid: "14638d50-b682-45f9-9ebf-da64467a16e0",
    has_errata: false,
    url: "https://ringsdb.com/card/19084",
    imagesrc: "/bundles/cards/19084.png",
    alive: true,
    current: false,
  },
  {
    pack_code: "MG",
    pack_name: "Mount Gundabad",
    type_code: "hero",
    type_name: "Hero",
    sphere_code: "tactics",
    sphere_name: "Tactics",
    position: 112,
    code: "19112",
    name: "Bilbo Baggins",
    traits: "Hobbit. Burglar. ",
    text: "<b>Response</b>: After Bilbo Baggins commits to the quest, choose an enemy in the staging area. Until the end of the phase, Bilbo Baggins gets +X [willpower] where X is that enemy’s [threat]. If the players quest successfully, deal 1 damage to that enemy (2 damage instead if it is guarding a card). ",
    is_unique: true,
    threat: 9,
    willpower: 1,
    attack: 1,
    defense: 2,
    health: 2,
    quantity: 1,
    deck_limit: 1,
    illustrator: "Tropa Entertainment",
    octgnid: "3844dc9e-8235-4eda-8799-e18fe2af44d4",
    has_errata: false,
    url: "https://ringsdb.com/card/19112",
    imagesrc: "/bundles/cards/19112.png",
    alive: true,
    current: false,
  },
  {
    pack_code: "Starter",
    pack_name: "Two-Player Limited Edition Starter",
    type_code: "hero",
    type_name: "Hero",
    sphere_code: "leadership",
    sphere_name: "Leadership",
    position: 1,
    code: "20001",
    name: "Aragorn",
    traits: "Dúnedain. Noble. Ranger.",
    text: "Sentinel.\n<b>Response:</b> After Aragorn commits to a quest, spend 1 resource from his resource pool to ready him.",
    flavor:
      '"I am Aragorn son of Arathorn; and if by life or death I can save you, I will."\n<cite>The Fellowship of the Ring</cite>',
    is_unique: true,
    threat: 12,
    willpower: 2,
    attack: 3,
    defense: 2,
    health: 5,
    quantity: 1,
    deck_limit: 1,
    illustrator: "John Stanko",
    octgnid: "cf2f9186-27ff-4d04-95da-5dc6e96a009d",
    has_errata: false,
    url: "https://ringsdb.com/card/20001",
    imagesrc: "/bundles/cards/20001.png",
    alive: true,
    current: false,
  },
  {
    pack_code: "Starter",
    pack_name: "Two-Player Limited Edition Starter",
    type_code: "hero",
    type_name: "Hero",
    sphere_code: "spirit",
    sphere_name: "Spirit",
    position: 3,
    code: "20003",
    name: "Nori",
    traits: "Dwarf.",
    text: "<b>Response</b>: After you play a <b><i>Dwarf</i></b> character from your hand, reduce your threat by 1.",
    flavor: 'Nori, at your service." -Nori, The Hobbit',
    is_unique: true,
    threat: 9,
    willpower: 2,
    attack: 1,
    defense: 2,
    health: 4,
    quantity: 1,
    deck_limit: 1,
    illustrator: "Blake Henriksen",
    octgnid: "d10872b6-6ae9-4253-b035-de3ec3806ebd",
    has_errata: false,
    url: "https://ringsdb.com/card/20003",
    imagesrc: "/bundles/cards/20003.png",
    alive: true,
    current: false,
  },
  {
    pack_code: "Starter",
    pack_name: "Two-Player Limited Edition Starter",
    type_code: "hero",
    type_name: "Hero",
    sphere_code: "lore",
    sphere_name: "Lore",
    position: 34,
    code: "20034",
    name: "Glorfindel",
    traits: "Noble. Noldor. Warrior.",
    text: "<b>Action</b>: Pay 1 resource from Glorfindel's pool to heal 1 damage on any character. (Limit once per round.)",
    flavor:
      '"You saw him for a moment as he is upon the other side: one of the mighty of the firstborn."\n-Gandalf, The Fellowship of the Ring',
    is_unique: true,
    threat: 12,
    willpower: 3,
    attack: 3,
    defense: 1,
    health: 5,
    quantity: 1,
    deck_limit: 1,
    illustrator: "Katherine Dinger",
    octgnid: "c3bda1bf-3f2e-4fb4-a36b-3e982123c9f9",
    has_errata: false,
    url: "https://ringsdb.com/card/20034",
    imagesrc: "/bundles/cards/20034.png",
    alive: true,
    current: false,
  },
  {
    pack_code: "Starter",
    pack_name: "Two-Player Limited Edition Starter",
    type_code: "hero",
    type_name: "Hero",
    sphere_code: "lore",
    sphere_name: "Lore",
    position: 35,
    code: "20035",
    name: "Bifur",
    traits: "Dwarf.",
    text: "<b>Action</b>: Pay 1 resource from a hero's resource pool to add 1 resource to Bifur's resource pool. Any player may trigger this ability. (Limit once per round.)",
    flavor: 'And winter comes after autumn." - Bifur, The Hobbit',
    is_unique: true,
    threat: 7,
    willpower: 2,
    attack: 1,
    defense: 2,
    health: 3,
    quantity: 1,
    deck_limit: 1,
    illustrator: "Rafał Hrynkiewicz",
    octgnid: "a511ccaf-b2c6-4e25-86ba-accd5d67b51b",
    has_errata: false,
    url: "https://ringsdb.com/card/20035",
    imagesrc: "/bundles/cards/20035.png",
    alive: true,
    current: false,
  },
  {
    pack_code: "ASitE",
    pack_name: "A Shadow in the East",
    type_code: "hero",
    type_name: "Hero",
    sphere_code: "leadership",
    sphere_name: "Leadership",
    position: 2,
    code: "21002",
    name: "Frodo Baggins",
    traits: "Hobbit.",
    text: "<b>Response</b>: After Frodo Baggins commits to the quest, spend 1 resource from his resource pool to ready another unique character committed to the quest. If you quest successfully this phase, reduce your threat by 1.",
    flavor:
      '"Keep your tempers and hold your hands to the last possible moment!"\r\n-The Return of the King',
    is_unique: true,
    threat: 7,
    willpower: 2,
    attack: 1,
    defense: 2,
    health: 2,
    quantity: 1,
    deck_limit: 1,
    illustrator: "Sara Biddle",
    octgnid: "f733522a-bcdd-466c-9565-0b4cba58701b",
    has_errata: false,
    url: "https://ringsdb.com/card/21002",
    imagesrc: "/bundles/cards/21002.png",
    alive: true,
    current: false,
  },
  {
    pack_code: "WaR",
    pack_name: "Wrath and Ruin",
    type_code: "hero",
    type_name: "Hero",
    sphere_code: "tactics",
    sphere_name: "Tactics",
    position: 1,
    code: "22001",
    name: "Thorin Stonehelm",
    traits: "Dwarf. Noble. Warrior.",
    text: "<b>Response</b>: After Thorin Stonehelm is declared as an attacker, discard the top card of your deck to deal 1 damage to an enemy engaged with you.",
    flavor:
      'Thorin III Stonehelm, Dain"s son, became King under the mountain.\n-The Return of the King',
    is_unique: true,
    threat: 9,
    willpower: 1,
    attack: 3,
    defense: 1,
    health: 4,
    quantity: 1,
    deck_limit: 1,
    illustrator: "Rafał Hrynkiewicz",
    octgnid: "e6e32f1f-fca8-44cc-8e04-0eaf6361b929",
    has_errata: false,
    url: "https://ringsdb.com/card/22001",
    imagesrc: "/bundles/cards/22001.png",
    alive: true,
    current: false,
  },
  {
    pack_code: "UtAM",
    pack_name: "Under the Ash Mountains",
    type_code: "hero",
    type_name: "Hero",
    sphere_code: "leadership",
    sphere_name: "Leadership",
    position: 81,
    code: "22081",
    name: "Gildor Inglorion",
    traits: "Noldor. Noble.",
    text: "<b>Action</b>: Pay 1 resource from Gildor Inglorion's resource pool to choose a player to draw 1 card (Limit once per round.)",
    flavor:
      '"Gildor Inglorion of the House of Finrod. We are Exiles, and most of our kindred have long ago departed..."\n-The Fellowship of the Ring',
    is_unique: true,
    threat: 9,
    willpower: 3,
    attack: 2,
    defense: 1,
    health: 3,
    quantity: 1,
    deck_limit: 1,
    illustrator: "Jason Jenicke",
    octgnid: "4eac6112-54ea-4a3e-851b-cd6456047dd2",
    has_errata: false,
    url: "https://ringsdb.com/card/22081",
    imagesrc: "/bundles/cards/22081.png",
    alive: true,
    current: false,
  },
  {
    pack_code: "TFoN",
    pack_name: "The Fortress of Nurn",
    type_code: "hero",
    type_name: "Hero",
    sphere_code: "spirit",
    sphere_name: "Spirit",
    position: 137,
    code: "22137",
    name: "Aragorn",
    traits: "Dúnedain. Ranger. Scout.",
    text: "Sentinel.\r\n<b>Action:</b> Exhaust Aragorn to choose a location in the staging area. Until the end of the phase, that location gets -X [threat], where X is Aragorn's [willpower]. If this effect reduces the location's [threat] to 0, place 1 progress on it. (Limit once per round.)",
    is_unique: true,
    threat: 12,
    willpower: 2,
    attack: 3,
    defense: 2,
    health: 5,
    quantity: 1,
    deck_limit: 1,
    illustrator: "Aleksander Karcz",
    octgnid: "950e710c-4b2f-4e65-9e5d-8f0f7390812c",
    has_errata: false,
    url: "https://ringsdb.com/card/22137",
    imagesrc: "/bundles/cards/22137.png",
    alive: true,
    current: false,
  },
  {
    pack_code: "TAP",
    pack_name: "ALeP - The Aldburg Plot",
    type_code: "hero",
    type_name: "Hero",
    sphere_code: "lore",
    sphere_name: "Lore",
    position: 1,
    code: "301001",
    name: "Fatty Bolger",
    traits: "Hobbit.",
    text: "<b>Setup</b>: Reduce your threat by 2.\r\n<b>Response</b>: Raise your threat by 4 and exhaust Fatty Bolger to cancel a non-unique enemy card just revealed from the encounter deck and add it to the victory display. (Limit once per game for the group.)",
    flavor:
      "Fatty Bolger had not been idle. As soon as he saw the dark shapes creep from the garden, he knew that he must run for it, or perish. —The Fellowship of the Ring",
    is_unique: true,
    threat: 7,
    willpower: 1,
    attack: 1,
    defense: 2,
    health: 3,
    quantity: 1,
    deck_limit: 1,
    illustrator: "Yang Zhao",
    octgnid: "151ba48a-1efd-451e-bba0-b49fa0566596",
    has_errata: false,
    url: "https://ringsdb.com/card/301001",
    imagesrc: "/bundles/cards/301001.png",
    alive: true,
    current: false,
  },
  {
    pack_code: "TGC",
    pack_name: "ALeP - The Glittering Caves",
    type_code: "hero",
    type_name: "Hero",
    sphere_code: "tactics",
    sphere_name: "Tactics",
    position: 102,
    code: "304102",
    name: "Glorfindel",
    traits: "Noldor. Noble. Warrior.",
    text: "Glorfindel gets +2 [attack] while attacking alone.\nGlorfindel gets +2 [attack] while attacking a unique enemy.",
    flavor:
      "Then Glorfindel leapt forward upon him and his golden armour gleamed strangely in the moon…\n—The Fall of Gondolin",
    is_unique: true,
    threat: 12,
    willpower: 3,
    attack: 3,
    defense: 1,
    health: 5,
    quantity: 1,
    deck_limit: 1,
    illustrator: "Steven Shan",
    octgnid: "9abb5216-a019-469b-95a5-ef4bec8601fe",
    has_errata: false,
    url: "https://ringsdb.com/card/304102",
    imagesrc: "/bundles/cards/304102.png",
    alive: true,
    current: false,
  },
  {
    pack_code: "BitI",
    pack_name: "ALeP - Blood in the Isen",
    type_code: "hero",
    type_name: "Hero",
    sphere_code: "neutral",
    sphere_name: "Neutral",
    position: 183,
    code: "306183",
    name: "Aragorn",
    traits: "Dúnedain. Ranger.",
    text: "Aragorn gains a resource icon matching each <b><i>Title</i></b> attachment attached to him.\n<b>Setup</b>: Search your collection for a <b><i>Title</i></b> attachment with a printed cost of 1 and attach it to Aragorn.\n<b>Action</b>: Ready a <b><i>Title</i></b> attachment with a printed cost of 1 attached to Aragorn. (Limit once per round.)",
    flavor: "",
    is_unique: true,
    threat: 12,
    willpower: 2,
    attack: 3,
    defense: 2,
    health: 5,
    quantity: 1,
    deck_limit: 1,
    illustrator: "Jan Pospíšil",
    octgnid: "2fd5d9f4-81e2-4af9-b3bf-5b7552173857",
    has_errata: false,
    url: "https://ringsdb.com/card/306183",
    imagesrc: "/bundles/cards/306183.png",
    alive: true,
    current: false,
  },
  {
    pack_code: "DoD",
    pack_name: "Dwarves of Durin",
    type_code: "hero",
    type_name: "Hero",
    sphere_code: "leadership",
    sphere_name: "Leadership",
    position: 1,
    code: "31001",
    name: "Dáin Ironfoot",
    traits: "Dwarf. Noble.",
    text: "While Dáin Ironfoot is ready, Dwarf characters get +1 [attack] and +1 [willpower].",
    flavor:
      '"You have not heard of Dáin and the dwarves of the Iron Hills?"\n-Bilbo Baggins, The Hobbit',
    is_unique: true,
    threat: 11,
    willpower: 1,
    attack: 2,
    defense: 3,
    health: 5,
    quantity: 1,
    deck_limit: 1,
    illustrator: "Tiziano Baracchi",
    octgnid: "347fa1ce-ec8d-43d9-a407-bc26d041b45e",
    has_errata: false,
    url: "https://ringsdb.com/card/31001",
    imagesrc: "/bundles/cards/31001.png",
    alive: true,
    current: false,
  },
  {
    pack_code: "DoD",
    pack_name: "Dwarves of Durin",
    type_code: "hero",
    type_name: "Hero",
    sphere_code: "lore",
    sphere_name: "Lore",
    position: 2,
    code: "31002",
    name: "Ori",
    traits: "Dwarf.",
    text: "If you control at least 5 Dwarf characters, draw 1 additional card at the beginning of the resource phase.",
    flavor:
      '"He could write well and speedily, and often used the Elvish characters."\n-Gimli, The Fellowship of the Ring',
    is_unique: true,
    threat: 8,
    willpower: 2,
    attack: 2,
    defense: 1,
    health: 3,
    quantity: 1,
    deck_limit: 1,
    illustrator: "Blake Henriksen",
    octgnid: "3f1fe728-ecc6-4aff-a056-31e3731e39c2",
    has_errata: false,
    url: "https://ringsdb.com/card/31002",
    imagesrc: "/bundles/cards/31002.png",
    alive: true,
    current: false,
  },
  {
    pack_code: "DoD",
    pack_name: "Dwarves of Durin",
    type_code: "hero",
    type_name: "Hero",
    sphere_code: "lore",
    sphere_name: "Lore",
    position: 3,
    code: "31003",
    name: "Bifur",
    traits: "Dwarf.",
    text: "<b>Action:</b> Pay 1 resource from a hero's resource pool to add 1 resource to Bifur's resource pool. Any player may trigger this ability. (Limit once per round.)",
    flavor: '"And winter comes after autumn." - Bifur, The Hobbit',
    is_unique: true,
    threat: 7,
    willpower: 2,
    attack: 1,
    defense: 2,
    health: 3,
    quantity: 1,
    deck_limit: 1,
    illustrator: "Magali Villeneuve",
    octgnid: "6047ca12-04ce-40db-b919-ef97fadb0430",
    has_errata: false,
    url: "https://ringsdb.com/card/31003",
    imagesrc: "/bundles/cards/31003.png",
    alive: true,
    current: false,
  },
  {
    pack_code: "DoD",
    pack_name: "Dwarves of Durin",
    type_code: "hero",
    type_name: "Hero",
    sphere_code: "spirit",
    sphere_name: "Spirit",
    position: 25,
    code: "31025",
    name: "Nori",
    traits: "Dwarf.",
    text: "<b>Response:</b> After you play a Dwarf character from your hand, reduce your threat by 1.",
    flavor: '"Nori, at your service."\n-Nori, The Hobbit',
    is_unique: true,
    threat: 9,
    willpower: 2,
    attack: 1,
    defense: 2,
    health: 4,
    quantity: 1,
    deck_limit: 1,
    illustrator: "Blake Henriksen",
    octgnid: "43aa19c5-4858-4217-8a16-826a52e8fb25",
    has_errata: false,
    url: "https://ringsdb.com/card/31025",
    imagesrc: "/bundles/cards/31025.png",
    alive: true,
    current: false,
  },
  {
    pack_code: "EoL",
    pack_name: "Elves of Lórien",
    type_code: "hero",
    type_name: "Hero",
    sphere_code: "leadership",
    sphere_name: "Leadership",
    position: 1,
    code: "32001",
    name: "Celeborn",
    traits: "Silvan. Noble.",
    text: "<b>Response:</b> After a Silvan ally enters play, that ally gets +1 [willpower], +1 [attack] and +1 [defense] until the end of the round.",
    flavor:
      '"...the lord of the Galadhrim is accounted wisest of the Elves of Middle-earth, and a giver of gifts beyond the power of kings." -Galadriel, The Fellowship of the Ring',
    is_unique: true,
    threat: 11,
    willpower: 3,
    attack: 2,
    defense: 2,
    health: 4,
    quantity: 1,
    deck_limit: 1,
    illustrator: "Magali Villeneuve",
    octgnid: "afec8b6f-6838-442e-b2a8-71537a25e05d",
    has_errata: false,
    url: "https://ringsdb.com/card/32001",
    imagesrc: "/bundles/cards/32001.png",
    alive: true,
    current: false,
  },
  {
    pack_code: "EoL",
    pack_name: "Elves of Lórien",
    type_code: "hero",
    type_name: "Hero",
    sphere_code: "spirit",
    sphere_name: "Spirit",
    position: 2,
    code: "32002",
    name: "Galadriel",
    traits: "Noldor. Noble.",
    text: "Galadriel cannot quest, attack, or defend. Allies you control do not exhaust to commit to the quest during the round they enter play.\n<b>Action:</b> Exhaust Galadriel to choose a player. That player reduces his threat by 1 and draws 1 card. (Limit once per round.)",
    flavor: "",
    is_unique: true,
    threat: 9,
    willpower: 4,
    attack: 0,
    defense: 0,
    health: 4,
    quantity: 1,
    deck_limit: 1,
    illustrator: "Magali Villeneuve",
    octgnid: "8ccfbcf2-676c-4e24-ab5e-fa479343ab39",
    has_errata: false,
    url: "https://ringsdb.com/card/32002",
    imagesrc: "/bundles/cards/32002.png",
    alive: true,
    current: false,
  },
  {
    pack_code: "EoL",
    pack_name: "Elves of Lórien",
    type_code: "hero",
    type_name: "Hero",
    sphere_code: "lore",
    sphere_name: "Lore",
    position: 3,
    code: "32003",
    name: "Haldir of Lórien",
    traits: "Silvan. Ranger. Scout.",
    text: "Ranged.\n<b>Combat Action:</b> If you have not engaged an enemy this round, exhaust Haldir of Lórien to declare him as an attacker (and resolve his attack) against an enemy not engaged with you. (Limit once per round.)",
    flavor: "",
    is_unique: true,
    threat: 9,
    willpower: 2,
    attack: 3,
    defense: 1,
    health: 3,
    quantity: 1,
    deck_limit: 1,
    illustrator: "Sebastian Giacobino",
    octgnid: "46fa971f-b0d9-48b5-a584-1213739adb66",
    has_errata: false,
    url: "https://ringsdb.com/card/32003",
    imagesrc: "/bundles/cards/32003.png",
    alive: true,
    current: false,
  },
  {
    pack_code: "EoL",
    pack_name: "Elves of Lórien",
    type_code: "hero",
    type_name: "Hero",
    sphere_code: "lore",
    sphere_name: "Lore",
    position: 31,
    code: "32031",
    name: "Elrond",
    traits: "Noldor. Noble.",
    text: "You may spend resources from Elrond's resource pool to pay for [spirit], [leadership], and [tactics] allies.\n<b>Response:</b> After a character is healed by another card effect, heal 1 damage on it.",
    flavor: '"But you do not stand alone."\n-The Fellowship of the Ring',
    is_unique: true,
    threat: 13,
    willpower: 3,
    attack: 2,
    defense: 3,
    health: 4,
    quantity: 1,
    deck_limit: 1,
    illustrator: "Magali Villeneuve",
    octgnid: "4fbd12f8-36b2-42c6-8df7-d507c1e87558",
    has_errata: false,
    url: "https://ringsdb.com/card/32031",
    imagesrc: "/bundles/cards/32031.png",
    alive: true,
    current: false,
  },
  {
    pack_code: "DoG",
    pack_name: "Defenders of Gondor",
    type_code: "hero",
    type_name: "Hero",
    sphere_code: "leadership",
    sphere_name: "Leadership",
    position: 1,
    code: "33001",
    name: "Boromir",
    traits: "Gondor. Warrior. Noble.",
    text: "While Boromir has at least 1 resource in his resource pool, Gondor allies get +1 [attack].",
    flavor:
      '"By our valour the wild fold of the East are still restrained, and the terror of Morgul kept at bay..." -The Fellowship of the Ring',
    is_unique: true,
    threat: 11,
    willpower: 1,
    attack: 3,
    defense: 2,
    health: 5,
    quantity: 1,
    deck_limit: 1,
    illustrator: "Magali Villeneuve",
    octgnid: "55a2193b-c458-4aa0-82ec-544a373a1dca",
    has_errata: false,
    url: "https://ringsdb.com/card/33001",
    imagesrc: "/bundles/cards/33001.png",
    alive: true,
    current: false,
  },
  {
    pack_code: "DoG",
    pack_name: "Defenders of Gondor",
    type_code: "hero",
    type_name: "Hero",
    sphere_code: "leadership",
    sphere_name: "Leadership",
    position: 2,
    code: "33002",
    name: "Prince Imrahil",
    traits: "Gondor. Noble.",
    text: "<b>Response:</b> After a character leaves play, ready Prince Imrahil. (Limit once per round.)",
    flavor:
      "But beyond, in the great fief of Belfalas, dwelt Prince Imrahil in his castle of Dol Amroth by the sea, and he was of high blood, and his fold also, tall men and proud with sea-grey eyes. -The Return of the King.",
    is_unique: true,
    threat: 11,
    willpower: 2,
    attack: 3,
    defense: 2,
    health: 4,
    quantity: 1,
    deck_limit: 1,
    illustrator: "David A. Nash",
    octgnid: "d61ab954-f8b8-4334-9d4a-297f58404b51",
    has_errata: false,
    url: "https://ringsdb.com/card/33002",
    imagesrc: "/bundles/cards/33002.png",
    alive: true,
    current: false,
  },
  {
    pack_code: "DoG",
    pack_name: "Defenders of Gondor",
    type_code: "hero",
    type_name: "Hero",
    sphere_code: "tactics",
    sphere_name: "Tactics",
    position: 3,
    code: "33003",
    name: "Mablung",
    traits: "Gondor. Ranger.",
    text: "<b>Response:</b> After you engage an enemy, add 1 resource to Mablung's resource pool. (Limit once per phase.)",
    flavor:
      "But the Captains of the West were well warned by their scouts, skilled men from Henneth Annûn led by Mablung...\n-The Return of the King",
    is_unique: true,
    threat: 10,
    willpower: 2,
    attack: 2,
    defense: 2,
    health: 4,
    quantity: 1,
    deck_limit: 1,
    illustrator: "Sebastian Giacobino",
    octgnid: "4930fbda-032d-4476-8b3a-e27ff28691f4",
    has_errata: false,
    url: "https://ringsdb.com/card/33003",
    imagesrc: "/bundles/cards/33003.png",
    alive: true,
    current: false,
  },
  {
    pack_code: "DoG",
    pack_name: "Defenders of Gondor",
    type_code: "hero",
    type_name: "Hero",
    sphere_code: "tactics",
    sphere_name: "Tactics",
    position: 27,
    code: "33027",
    name: "Beregond",
    traits: "Gondor. Warrior.",
    text: "Sentinel.\nLower the cost to play Weapon and Armor attachments on Beregond by 2.",
    flavor:
      '"It is over-late to send for aid when you are already besieged." -The Return of the King',
    is_unique: true,
    threat: 10,
    willpower: 0,
    attack: 1,
    defense: 4,
    health: 4,
    quantity: 1,
    deck_limit: 1,
    illustrator: "Magali Villeneuve",
    octgnid: "b6b8da1c-5269-440b-9015-b5748a91c358",
    has_errata: false,
    url: "https://ringsdb.com/card/33027",
    imagesrc: "/bundles/cards/33027.png",
    alive: true,
    current: false,
  },
  {
    pack_code: "DoG",
    pack_name: "Defenders of Gondor",
    type_code: "hero",
    type_name: "Hero",
    sphere_code: "lore",
    sphere_name: "Lore",
    position: 28,
    code: "33028",
    name: "Faramir",
    traits: "Gondor. Ranger. Noble.",
    text: "Ranged.\nFaramir gets +1 [attack] for each enemy in the staging area.",
    flavor:
      '"The road may pass, but they shall not! Not while Faramir is Captain."\n-Mablung, The Two Towers',
    is_unique: true,
    threat: 11,
    willpower: 2,
    attack: 2,
    defense: 2,
    health: 5,
    quantity: 1,
    deck_limit: 1,
    illustrator: "Magali Villeneuve",
    octgnid: "8fcb55c3-2996-4c13-b120-2b0c31f62d21",
    has_errata: false,
    url: "https://ringsdb.com/card/33028",
    imagesrc: "/bundles/cards/33028.png",
    alive: true,
    current: false,
  },
  {
    pack_code: "RoR",
    pack_name: "Riders of Rohan",
    type_code: "hero",
    type_name: "Hero",
    sphere_code: "tactics",
    sphere_name: "Tactics",
    position: 1,
    code: "34001",
    name: "Éomer",
    traits: "Rohan. Noble. Warrior.",
    text: "<b>Response:</b> After a character leaves play, Éomer gets +2 [attack] until the end of the round. (Limit once per round.)",
    flavor:
      '"I am named Éomer son of Éomund, and am called the Third Marshal of Riddermark." -The Two Towers',
    is_unique: true,
    threat: 10,
    willpower: 1,
    attack: 3,
    defense: 2,
    health: 4,
    quantity: 1,
    deck_limit: 1,
    illustrator: "Magali Villeneuve",
    octgnid: "e87c3473-e107-40dd-9af7-b01f35176ea0",
    has_errata: false,
    url: "https://ringsdb.com/card/34001",
    imagesrc: "/bundles/cards/34001.png",
    alive: true,
    current: false,
  },
  {
    pack_code: "RoR",
    pack_name: "Riders of Rohan",
    type_code: "hero",
    type_name: "Hero",
    sphere_code: "tactics",
    sphere_name: "Tactics",
    position: 2,
    code: "34002",
    name: "Hirgon",
    traits: "Gondor. Scout.",
    text: "<b>Response:</b> After Hirgon quests successfully, play a [tactics] ally from your hand, reducing its cost by 1 (to a minimum of 1). Then, you may raise your threat by 1 to give that ally +1 [attack] and +1 [defense] until the end of the round.",
    flavor:
      '"Hirgon I am, errand-rider of Denethor, who bring you this token of war."\n-The Return of the King',
    is_unique: true,
    threat: 9,
    willpower: 2,
    attack: 2,
    defense: 1,
    health: 4,
    quantity: 1,
    deck_limit: 1,
    illustrator: "Aleksander Karcz",
    octgnid: "974d6f07-6192-4275-a030-7d590426c286",
    has_errata: false,
    url: "https://ringsdb.com/card/34002",
    imagesrc: "/bundles/cards/34002.png",
    alive: true,
    current: false,
  },
  {
    pack_code: "RoR",
    pack_name: "Riders of Rohan",
    type_code: "hero",
    type_name: "Hero",
    sphere_code: "spirit",
    sphere_name: "Spirit",
    position: 3,
    code: "34003",
    name: "Lothíriel",
    traits: "Gondor. Noble.",
    text: "If Éomer is in play, Lothíriel gains the Rohan trait.\n<b>Response:</b> After Lothíriel commits to a quest, choose an ally in your hand. If that ally shares a Trait with her, put that ally into play exhausted and committed to the quest. At the end of the phase, if that ally is still in play, shuffle it into your deck.",
    flavor: "",
    is_unique: true,
    threat: 8,
    willpower: 3,
    attack: 1,
    defense: 1,
    health: 3,
    quantity: 1,
    deck_limit: 1,
    illustrator: "Álvaro Calvo Escudero",
    octgnid: "2221ee74-436d-44fa-84bc-27b3653ef2ba",
    has_errata: false,
    url: "https://ringsdb.com/card/34003",
    imagesrc: "/bundles/cards/34003.png",
    alive: true,
    current: false,
  },
  {
    pack_code: "RoR",
    pack_name: "Riders of Rohan",
    type_code: "hero",
    type_name: "Hero",
    sphere_code: "spirit",
    sphere_name: "Spirit",
    position: 27,
    code: "34027",
    name: "Fastred",
    traits: "Rohan. Warrior.",
    text: "<b>Response:</b> After Fastred defends an enemy attack, return that enemy to the staging area to reduce your threat by 2. (Limit once per phase.)",
    flavor:
      "\"King's man! King's man!\" his heart cried within him.\n-The Return of the King",
    is_unique: true,
    threat: 9,
    willpower: 1,
    attack: 2,
    defense: 3,
    health: 3,
    quantity: 1,
    deck_limit: 1,
    illustrator: "Lukasz Jaskolski",
    octgnid: "a8d9c225-1404-4a7e-9aa3-ea887510be63",
    has_errata: false,
    url: "https://ringsdb.com/card/34027",
    imagesrc: "/bundles/cards/34027.png",
    alive: true,
    current: false,
  },
  {
    pack_code: "TSotS",
    pack_name: "ALeP - The Scouring of the Shire",
    type_code: "hero",
    type_name: "Hero",
    sphere_code: "fellowship",
    sphere_name: "Fellowship",
    position: 6,
    code: "500006",
    name: "Frodo Baggins",
    traits: "Hobbit.",
    text: "The first player gains control of Frodo Baggins.\n<b>Response</b>: After Frodo Baggins is declared as a defender, spend 1 [fellowship] resource to reduce your threat by the attacking enemy’s [threat]. Until the end of the round, that enemy cannot take damage.\n<b>If Frodo Baggins leaves play, the players lose the game.</b>",
    flavor: "",
    is_unique: true,
    threat: 0,
    willpower: 2,
    attack: 1,
    defense: 2,
    health: 2,
    quantity: 1,
    deck_limit: 1,
    illustrator: "Sara Biddle",
    octgnid: "788cdbe8-2142-4216-a8e4-d4172d0aafe2",
    has_errata: false,
    url: "https://ringsdb.com/card/500006",
    imagesrc: "/bundles/cards/500006.png",
    alive: true,
    current: false,
  },
  {
    pack_code: "TSotS",
    pack_name: "ALeP - The Scouring of the Shire",
    type_code: "hero",
    type_name: "Hero",
    sphere_code: "leadership",
    sphere_name: "Leadership",
    position: 987,
    code: "500987",
    name: "Frodo Baggins",
    traits: "Hobbit.",
    text: "<b>Response</b>: After Frodo Baggins commits to the quest, spend 1 resource from his resource pool to ready another unique character committed to the quest. If you quest successfully this phase, reduce your threat by 1.",
    flavor: "",
    is_unique: true,
    threat: 7,
    willpower: 2,
    attack: 1,
    defense: 2,
    health: 2,
    quantity: 1,
    deck_limit: 1,
    illustrator: "Lukasz Jaskolski",
    octgnid: "247bb211-bf15-4627-99e8-914a8f1ca1bf",
    has_errata: false,
    url: "https://ringsdb.com/card/500987",
    imagesrc: "/bundles/cards/500987.png",
    alive: true,
    current: false,
  },
  {
    pack_code: "TNaN",
    pack_name: "ALeP - The Nine are Abroad",
    type_code: "hero",
    type_name: "Hero",
    sphere_code: "spirit",
    sphere_name: "Spirit",
    position: 993,
    code: "501993",
    name: "Glorfindel",
    traits: "Noldor. Noble. Warrior.",
    text: "<b>Forced</b>: After Glorfindel exhausts to commit to a quest, raise your threat by 1.",
    flavor: "",
    is_unique: true,
    threat: 5,
    willpower: 3,
    attack: 3,
    defense: 1,
    health: 5,
    quantity: 1,
    deck_limit: 1,
    illustrator: "Jan Pospíšil",
    octgnid: "76c3de5d-12c5-4190-99c8-16a6903a3851",
    has_errata: false,
    url: "https://ringsdb.com/card/501993",
    imagesrc: "/bundles/cards/501993.png",
    alive: true,
    current: false,
  },
  {
    pack_code: "TSoEr",
    pack_name: "ALeP - The Siege of Erebor",
    type_code: "hero",
    type_name: "Hero",
    sphere_code: "spirit",
    sphere_name: "Spirit",
    position: 991,
    code: "502991",
    name: "Dáin Ironfoot",
    traits: "Dwarf. Noble. Warrior.",
    text: "While Dáin Ironfoot is defending, he gains: “<b>Action</b>: Discard the top card of your deck to give Dáin Ironfoot +1 [defense] for this attack. (Limit 3 times per phase.)”",
    flavor: "",
    is_unique: true,
    threat: 11,
    willpower: 1,
    attack: 2,
    defense: 3,
    health: 5,
    quantity: 1,
    deck_limit: 1,
    illustrator: "Surya Prasetya",
    octgnid: "d77fffd8-292e-47d6-99a3-05f50d26069b",
    has_errata: false,
    url: "https://ringsdb.com/card/502991",
    imagesrc: "/bundles/cards/502991.png",
    alive: true,
    current: false,
  },
  {
    pack_code: "TSoEr",
    pack_name: "ALeP - The Siege of Erebor",
    type_code: "hero",
    type_name: "Hero",
    sphere_code: "tactics",
    sphere_name: "Tactics",
    position: 992,
    code: "502992",
    name: "Brand son of Bain",
    traits: "Dale.",
    text: "Ranged. <b>Response</b>: After Brand son of Bain attacks and defeats an enemy engaged with another player, choose and ready one of that player’s characters.",
    flavor: "",
    is_unique: true,
    threat: 10,
    willpower: 2,
    attack: 3,
    defense: 2,
    health: 3,
    quantity: 1,
    deck_limit: 1,
    illustrator: "Surya Prasetya",
    octgnid: "937dd499-1edb-4e66-b0c0-db768e2b8b61",
    has_errata: false,
    url: "https://ringsdb.com/card/502992",
    imagesrc: "/bundles/cards/502992.png",
    alive: true,
    current: false,
  },
  {
    pack_code: "TSoEr",
    pack_name: "ALeP - The Siege of Erebor",
    type_code: "hero",
    type_name: "Hero",
    sphere_code: "tactics",
    sphere_name: "Tactics",
    position: 993,
    code: "502993",
    name: "Brand son of Bain",
    traits: "Dale. Noble. Warrior.",
    text: "Ranged. <b>Response</b>: After Brand son of Bain attacks and destroys an enemy engaged with a player, ready one of that player’s characters. (Limit once per phase.)",
    is_unique: true,
    threat: 10,
    willpower: 2,
    attack: 3,
    defense: 2,
    health: 3,
    quantity: 1,
    deck_limit: 1,
    illustrator: "Surya Prasetya",
    octgnid: "c709e7bf-1889-4b76-b7c8-4632c3509a88",
    has_errata: false,
    url: "https://ringsdb.com/card/502993",
    imagesrc: "/bundles/cards/502993.png",
    alive: true,
    current: false,
  },
  {
    pack_code: "MotKA",
    pack_name: "Messenger of the King Allies",
    type_code: "hero",
    type_name: "Hero",
    sphere_code: "tactics",
    sphere_name: "Tactics",
    position: 8,
    code: "99131008",
    name: "(MotK) Bofur",
    traits: "Dwarf.",
    text: "<b>Action:</b> Exhaust Bofur to search the top 5 cards of your deck for 1 <b><i>Weapon</i></b> attachment. Add that card to your hand and shuffle the other cards back into your deck.",
    is_unique: true,
    threat: 7,
    willpower: 2,
    attack: 2,
    defense: 0,
    health: 3,
    quantity: 1,
    deck_limit: 1,
    illustrator: "David A. Nash",
    octgnid: "51223bd0-ffd1-11df-a976-1801204c9019",
    has_errata: false,
    url: "https://ringsdb.com/card/99131008",
    imagesrc: "/bundles/cards/99131008.png",
    alive: true,
    current: false,
  },
  {
    pack_code: "MotKA",
    pack_name: "Messenger of the King Allies",
    type_code: "hero",
    type_name: "Hero",
    sphere_code: "leadership",
    sphere_name: "Leadership",
    position: 4,
    code: "99144004",
    name: "(MotK) Anborn",
    traits: "Gondor. Ranger.",
    text: "<b>Response:</b> After an enemy is added to the staging area, exhaust Anborn to give that enemy +5 engagement cost until the end of the round. Then, deal 1 damage to that enemy.",
    flavor: '"Now I have him at arrow-point." <cite>The Two Towers</cite>',
    is_unique: true,
    threat: 8,
    willpower: 1,
    attack: 3,
    defense: 1,
    health: 3,
    quantity: 1,
    deck_limit: 1,
    illustrator: "Owen William Weber",
    octgnid: "c8b5dd1c-82bc-4733-be1a-484a6e87c3c0",
    has_errata: false,
    url: "https://ringsdb.com/card/99144004",
    imagesrc: "/bundles/cards/99144004.png",
    alive: true,
    current: false,
  },
  {
    pack_code: "MotKA",
    pack_name: "Messenger of the King Allies",
    type_code: "hero",
    type_name: "Hero",
    sphere_code: "tactics",
    sphere_name: "Tactics",
    position: 6,
    code: "99146006",
    name: "(MotK) Elfhelm",
    traits: "Rohan. Warrior.",
    text: "<b>Action:</b> Spend 1 resource from a <b><i>Rohan</i></b> hero's resource pool to put Elfhelm into play from your hand under your control. At the end of the phase, discard Elfhelm if he is still in play.",
    flavor:
      '"...my lord sends word that we must set ourselves in readiness; orders may come for a sudden move." <cite>The Return of the King</cite>',
    is_unique: true,
    threat: 8,
    willpower: 1,
    attack: 2,
    defense: 2,
    health: 3,
    quantity: 1,
    deck_limit: 1,
    illustrator: "Javier Charro Martinez",
    octgnid: "0ff72c0f-a6d6-48d3-8781-1988a7e3ba11",
    has_errata: false,
    url: "https://ringsdb.com/card/99146006",
    imagesrc: "/bundles/cards/99146006.png",
    alive: true,
    current: false,
  },
  {
    pack_code: "MotKA",
    pack_name: "Messenger of the King Allies",
    type_code: "hero",
    type_name: "Hero",
    sphere_code: "lore",
    sphere_name: "Lore",
    position: 5,
    code: "9921005",
    name: "(MotK) Faramir",
    traits: "Gondor. Noble. Ranger.",
    text: "<b>Response</b>: After Faramir enters play, choose a non-unique enemy in the staging area. Engage that enemy and deal 2 damage to it (4 damage instead if it has an attachment on it).",
    flavor:
      '"There will be hard handstrokes nigh at hand ere the day is full."\n-The Two Towers',
    is_unique: true,
    threat: 8,
    willpower: 2,
    attack: 1,
    defense: 2,
    health: 3,
    quantity: 1,
    deck_limit: 1,
    illustrator: "Greg Bobrowski",
    octgnid: "f43d5b83-4136-4be8-af89-71f883f32563",
    has_errata: false,
    url: "https://ringsdb.com/card/9921005",
    imagesrc: "/bundles/cards/9921005.png",
    alive: true,
    current: false,
  },
];
